! GILDAS MAPPING SCRIPT

let name "output_residual"

say ""
say "go uvmap"
go uvmap

say ""
say "go noise"
go noise

let spacing noise

say ""
say "examine map_size"
exam map_size

say ""
say "examine map_cell"
exam map_cell

say ""
say "examine size"
exam size

say ""
say "examine noise"
exam noise

say ""
say "fits"
fits 'name'.lmv.fits from 'name'.lmv /overwrite

say ""
say "go view"
go view
let do_header YES
go nice

hardcopy "output_residual.eps" /overwrite
if (FILE("output_residual.eps")) then
sys "ps2pdf -dEPSCrop output_residual.eps"
endif
