! 
! Task UV_FIT (new version R. Lucas)
! 6 parameters needed for all functions
!
TASK\CHARACTER "UV Table: "               UVTABLE$     "split_z35_68_spw0_width128.uvt"
TASK\INTEGER   "Channels: "               CHANNEL$[2]   1 1
TASK\REAL      "UV Range: "              UV_RANGE$[2]   10 200
TASK\CHARACTER "Result Fits Table: "       RESULT$     "output_uv_fit.uvfit"
TASK\CHARACTER "Residual UV Table: "    RESIDUALS$     "output_residual.uvt"
TASK\INTEGER   "Number of Functions"           NF$      1
! 
! Functions 
! (POINT, C_GAUSS, E_GAUSS, C_DISK, 
!  E_DISK, RING, EXP, POWER-2, POWER-3)
! 
! --- begin repeat ---
! 
! --- 01
! 
TASK\CHARACTER "Function"            FUNCT01$       POINT
TASK\REAL      "Parameters"          PARAM01$[7]    0.0000000 0.0000000 1.0 0.0 0.0 0.0 0
TASK\REAL      "Starting range"      RANGE01$[7]    0 0 0 0 0 0 0
TASK\INTEGER   "number of starts"    START01$[7]    -1 -1 0 0 0 0 0
TASK\LOGICAL   "Subtract function"   SUBSF01$       YES
! 
! --- end repeat ---
! 
TASK\GO
