! GILDAS MAPPING SCRIPT

let name "split_z35_68_spw0_width128"

say ""
say "go uvmap"
go uvmap

say ""
say "go noise"
go noise

let spacing noise

say ""
say "examine map_size"
exam map_size

say ""
say "examine map_cell"
exam map_cell

say ""
say "examine size"
exam size

say ""
say "examine noise"
exam noise

say ""
say "fits"
fits 'name'.lmv.fits from 'name'.lmv /overwrite

say ""
say "go view"
go view
let do_header no
go nice

hardcopy "split_z35_68_spw0_width128.eps" /overwrite
if (FILE("split_z35_68_spw0_width128.eps")) then
sys "ps2pdf -dEPSCrop split_z35_68_spw0_width128.eps"
endif
