! 
! Task UV_FIT (new version R. Lucas)
! 6 parameters needed for all functions
!
TASK\CHARACTER "UV Table: "                     UVTABLE$       "NAME"
TASK\INTEGER   "Channels: "                     CHANNEL$[2]     1 200
TASK\REAL      "UV Range: "                     UV_RANGE$[2]    0 36000
TASK\CHARACTER "Result Fits Table: "            RESULT$        "OUTPUT_NAME.uvfit"
TASK\CHARACTER "Residual UV Table: "            RESIDUALS$     ""
TASK\INTEGER   "Number of Functions"            NF$             2
! 
! Functions 
! (POINT, C_GAUSS, E_GAUSS, C_DISK, 
!  E_DISK, RING, EXP, POWER-2, POWER-3)
! 
! --- begin repeat ---
! 
! --- 01
! 
TASK\CHARACTER "Function"            FUNCT01$       C_GAUSS
TASK\REAL      "Parameters"          PARAM01$[7]    9.577 5.654 1.0 1.0 0.0 0.0 0
TASK\REAL      "Starting range"      RANGE01$[7]    0 0 0 0 0 0 0
TASK\INTEGER   "number of starts"    START01$[7]    -1 -1 0 -1 -1 0 0
TASK\LOGICAL   "Subtract function"   SUBSF01$       NO
! 
! --- 02
! 
TASK\CHARACTER "Function"            FUNCT02$       C_GAUSS
TASK\REAL      "Parameters"          PARAM02$[7]    -1.850 -2.250 1.0 1.0 0.0 0.0 0
TASK\REAL      "Starting range"      RANGE02$[7]    0 0 0 0 0 0 0
TASK\INTEGER   "number of starts"    START02$[7]    -1 -1 0 -1 -1 0 0
TASK\LOGICAL   "Subtract function"   SUBSF02$       NO
! 
! --- end repeat ---
! 
TASK\GO
